/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#4d4637',
        'surface-bright': '#3a3939',
        'surface-container': '#201f1f',
        'surface-main': '#111111',
        'surface-container-highest': '#353534',
        'surface-container-low': '#1c1b1b',
        'surface-card': '#161616',
        'surface-container-high': '#2a2a2a',
        'surface-container-lowest': '#0e0e0e',
        'surface-variant': '#353534',
        surface: '#131313',
        background: '#131313',
        outline: '#99907e',
        primary: '#e6c364',
        'on-primary': '#3d2e00',
        'primary-container': '#c9a84c',
        'on-primary-container': '#503d00',
        'inverse-primary': '#755b00',
        secondary: '#e2c375',
        'on-secondary': '#3d2e00',
        'secondary-container': '#5b4601',
        'on-secondary-container': '#d3b568',
        tertiary: '#b9c4ff',
        'on-tertiary': '#1e2b66',
        'tertiary-container': '#9ba8eb',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5b2',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'surface-tint': '#e6c364',
      },
      fontFamily: {
        garamond: ['"EB Garamond"', 'serif'],
        montserrat: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'button-text': ['14px', { lineHeight: '1', letterSpacing: '3px', fontWeight: '600' }],
        'price-tag': ['20px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'section-gap': '80px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
}
